drop table LEBEDEV_MA.error_logging purge;

--Таблица логов
create table LEBEDEV_MA.error_logging(
    id_log number generated by default as identity
    (start with 1 maxvalue 9999999999999999999999999999 minvalue 1 nocycle nocache noorder) primary key,
    log_user varchar2(100) default user,
    log_date date default sysdate,
    object_name varchar2(200),
    log_type varchar2(1000),
    params varchar2(4000)
)
partition by range (log_date) (
    partition part_first values less than (to_date('24.12.2021 12:00', 'dd.mm.yyyy hh24:mi')),
    partition part_second values less than (to_date('24.01.2022 12:00', 'dd.mm.yyyy hh24:mi')),
    partition part_third values less than (to_date('24.02.2022 12:00', 'dd.mm.yyyy hh24:mi')),
    partition part_max values less than (maxvalue)
);

--Просмотр всех секций
select * from sys.user_tab_partitions;

--Процедура создания лога
create or replace procedure LEBEDEV_MA.add_error_log(
    p_object_name varchar2,
    p_params varchar2,
    p_log_type varchar2 default 'common'
)
as
pragma autonomous_transaction;
begin
    insert into LEBEDEV_MA.error_logging(object_name, log_type, params)
    values (p_object_name, p_log_type, p_params);
    commit;
    DBMS_OUTPUT.PUT_LINE('Было выброшено исключение, см. логи');
end;

--Процедура со вставкой не всех данных, где вставка NULL невозможна, для проверки логирования
create or replace procedure LEBEDEV_MA.add_patient_fail(
    p_value number default 88005553535
)
as
begin
    insert into LEBEDEV_MA.PATIENTS (PHONENUMBER) values (p_value);
exception
    when others then
    LEBEDEV_MA.add_error_log( 'LEBEDEV_MA.add_patient_fail',
                '{"error":"' || sqlerrm
                ||'","backtrace":"' || dbms_utility.format_error_backtrace()
                ||'"}');
end;

--В анонимной блоке выполняем фэйл метод
begin
    LEBEDEV_MA.add_patient_fail();
end;

--Проверяем таблицу
select * from LEBEDEV_MA.error_logging;

--Удалим секцию первую
alter table LEBEDEV_MA.error_logging drop partition part_first;

--Вставляем ещё 3 секции путём деления последней
alter table LEBEDEV_MA.error_logging
split partition part_max at (to_date('24.03.2022 12:00', 'dd.mm.yyyy hh24:mi'))
into (partition part_fourth, partition part_max);
alter table LEBEDEV_MA.error_logging
split partition part_max at (to_date('24.04.2022 12:00', 'dd.mm.yyyy hh24:mi'))
into (partition part_fifth, partition part_max);
alter table LEBEDEV_MA.error_logging
split partition part_max at (to_date('24.05.2022 12:00', 'dd.mm.yyyy hh24:mi'))
into (partition part_sixth, partition part_max);

--Проверяем создание секций
select * from sys.user_tab_partitions;

--Пересобираем индекс
alter index LEBEDEV_MA.SYS_C0029057 rebuild;

--Снова в анонимной блоке выполняем фэйл метод
begin
    LEBEDEV_MA.add_patient_fail();
end;

--Убеждаемся, что данные заносятся
select * from LEBEDEV_MA.error_logging;